@api = http://localhost:5000

###
POST {{api}}/compilar
Content-Type: application/json

{
    "code": "println(uppercase(\"hola\")); \n println(lowercase(\"MUNdo\"));"
}

### Desarrollo
GET {{api}}/dev